
CREATE TABLE [dbo].[ReceipeMaster](
	[ReceipeId] [int] IDENTITY(1,1) NOT NULL,
	[ReceipeName] [nvarchar](50) NULL,
	[Description] [nvarchar](max) NULL,
	[ProductId] [int] NULL,
	[IsActive] [bit] NULL,
 CONSTRAINT [PK_ReceipeMaster] PRIMARY KEY CLUSTERED 
(
	[ReceipeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
